apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: chronos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: chronos/worker-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: worker-service-config
                optional: true
            - secretRef:
                name: worker-service-secret
                optional: true
