# ===============================
# Server
# ===============================
server.port=8083
spring.application.name=scheduler-service

# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/chronos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ----- HikariCP -----
spring.datasource.hikari.maximum-pool-size=7
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1700000

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# ===============================
# Scheduler
# ===============================
scheduler.fixed-rate=5000
scheduler.lock-key=chronos:scheduler:lock
scheduler.lock-expiry=10000

queue.name=chronos-jobs-queue

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.example.chronos=DEBUG